{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config
    ./disko.nix                    # optional: declarative disk layout (see comments)

    ../../apps/server/system/base.nix
    ../../apps/server/system/networking.nix
    ../../apps/server/system/users.nix
    ../../apps/server/system/sops.nix

    ../../apps/server/services/nextcloud.nix
    ../../apps/server/services/pihole.nix
    ../../apps/server/services/immich.nix
    ../../apps/server/services/calibre.nix
    ../../apps/server/services/wireguard.nix
    ../../apps/server/services/nginx.nix
    ../../apps/server/services/duckdns.nix
  ];

  # ── Machine identity ───────────────────────────────────────────────
  networking.hostName = "rocky";

  # ── Host-level overrides (override module defaults here) ───────────
  #
  # Example: disable a service you don't want on this host:
  #   services.immich.enable = false;
  #
  # Example: change the Nextcloud data dir:
  #   services.nextcloud.datadir = "/data/nextcloud";
}
