# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Display rotation
  boot.kernelParams = [
      # The GPD Pocket 4 uses a tablet LTPS display, that is mounted rotated 90° counter-clockwise
      "fbcon=rotate:1"
      "video=eDP-1:panel_orientation=right_side_up"
    ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/65a0012d-8bfb-4680-889b-28d09aca13da";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f50ac571-51bd-497f-84d1-451ae72a5813".device = "/dev/disk/by-uuid/f50ac571-51bd-497f-84d1-451ae72a5813";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E156-C953";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b5007990-c742-4024-8154-8f0df3f61ec9"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp196s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp195s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
