# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7c2c223e-4fb2-41c4-a738-083f89d0b7b9";
      fsType = "ext4";
      options = [ 
        # If you don't have this options attribute, it'll default to "defaults"
        # boot options for fstab. Search up fstab mount options you can use
        "users" # Allows any user to mount and unmount
        "nofail" # Prevent system from failing if this drive doesn't mount
        "x-gvfs-show" # Allows the mounted partition to be shown in the file explorer
        "exec"
      ];
    };

  boot.initrd.luks.devices."luks-b393b9dd-d475-45c2-8646-c2f848f48bd1".device = "/dev/disk/by-uuid/b393b9dd-d475-45c2-8646-c2f848f48bd1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/43B1-98F5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/pool/Games" =
    {
      device = "/dev/disk/by-uuid/d3d21f40-34da-4731-b2e2-4dca1e60066a";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/37f1877f-4efa-4700-8ef4-9a01db355fa3"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
