;;; post-init.el --- Packages configuration for Minimal Emacs Config -*- no-byte-compile: t; lexical-binding: t; -*-

(defvar glz/platform
  (cond ((eq system-type 'windows-nt) 'windows)
        ((eq system-type 'gnu/linux)  'linux)
        ((eq system-type 'android)    'android)
        (t 'linux))
  "Current platform symbol: windows, linux, or android.")

(defvar glz/enable-org-roam       (memq glz/platform '(linux)))
(defvar glz/enable-forge          (memq glz/platform '(linux)))
(defvar glz/enable-nix            (memq glz/platform '(linux)))
(defvar glz/enable-testfall       (memq glz/platform '(windows)))
(defvar glz/enable-anforderungen  (memq glz/platform '(windows)))
(defvar glz/enable-canape-par     t)

(defvar glz/org-directory
  (pcase glz/platform
    ('windows "~/Documents/PKDB_Org/")
    ('linux   "~/Documents/PKDB_Org/")
    ('android "~/storage/shared/Documents/PKDB_Org/"))
  "Root directory for all org files.")

;; On Windows, Emacs GUI does not inherit the system PATH.
;; Add Git's unix tools so diff, grep, find, etc. are available to all packages.
(when (eq glz/platform 'windows)
  (let ((git-bin "C:/Program Files/Git/usr/bin"))
    (when (file-directory-p git-bin)
      (add-to-list 'exec-path git-bin)
      (setenv "PATH" (concat git-bin ";" (getenv "PATH"))))))

(defun glz/display-startup-time ()
  (message "Emacs loaded in %s with %d garbage collections."
           (format "%.2f seconds"
                   (float-time (time-subtract after-init-time before-init-time)))
           gcs-done))

(add-hook 'emacs-startup-hook #'glz/display-startup-time)

(column-number-mode 1)

(setq visible-bell t)

(setq-default indent-tabs-mode nil
              tab-width 2)

(defun glz/prog-mode-configs ()
  "Personal adjustments for programming modes."
  (display-line-numbers-mode))

(add-hook 'prog-mode-hook #'glz/prog-mode-configs)

(setq initial-major-mode 'lisp-interaction-mode)
(setq initial-scratch-message
      ";; This buffer is for text that is not saved, and for Lisp evaluation.\n;; To create a file, visit it with `\\[find-file]' and enter text in its buffer.\n\n")

(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

(use-package compile-angel
  :demand t
  :config
  (setq package-native-compile nil)
  (setq compile-angel-verbose t)

  ;; Exclude init files from compilation to avoid subtle issues
  (push "/init.el" compile-angel-excluded-files)
  (push "/early-init.el" compile-angel-excluded-files)
  (push "/pre-init.el" compile-angel-excluded-files)
  (push "/post-init.el" compile-angel-excluded-files)
  (push "/pre-early-init.el" compile-angel-excluded-files)
  (push "/post-early-init.el" compile-angel-excluded-files)
  ;; customs.el is generated by Custom and has no lexical-binding directive
  (push "/customs.el" compile-angel-excluded-files)

  (compile-angel-on-load-mode 1))

(use-package doom-themes
  :config
  (let ((inhibit-redisplay t))
    (mapc #'disable-theme custom-enabled-themes)
    (load-theme 'doom-dracula t)))

(use-package all-the-icons
  :commands all-the-icons-install-fonts)

(use-package doom-modeline
  :commands doom-modeline-mode
  :hook (after-init . doom-modeline-mode)
  :custom (doom-modeline-height 15))

(use-package autorevert
  :ensure nil
  :commands (auto-revert-mode global-auto-revert-mode)
  :hook (after-init . global-auto-revert-mode)
  :init
  (setq auto-revert-interval 3)
  (setq auto-revert-remote-files nil)
  (setq auto-revert-use-notify t)
  (setq auto-revert-avoid-polling nil))

(use-package recentf
  :ensure nil
  :commands (recentf-mode recentf-cleanup)
  :hook (after-init . recentf-mode)
  :init
  (setq recentf-auto-cleanup (if (daemonp) 300 'never))
  (setq recentf-exclude
        (list "\\.tar$" "\\.tbz2$" "\\.tbz$" "\\.tgz$" "\\.bz2$"
              "\\.bz$" "\\.gz$" "\\.gzip$" "\\.xz$" "\\.zip$"
              "\\.7z$" "\\.rar$"
              "COMMIT_EDITMSG\\'"
              "\\.\\(?:gz\\|gif\\|svg\\|png\\|jpe?g\\|bmp\\|xpm\\)$"
              "-autoloads\\.el$" "autoload\\.el$"))
  :config
  (add-hook 'kill-emacs-hook #'recentf-cleanup -90))

(use-package savehist
  :ensure nil
  :commands (savehist-mode savehist-save)
  :hook (after-init . savehist-mode)
  :init
  (setq history-length 300)
  (setq savehist-autosave-interval 600))

(use-package saveplace
  :ensure nil
  :commands (save-place-mode save-place-local-mode)
  :hook (after-init . save-place-mode)
  :init
  (setq save-place-limit 400))

(use-package vertico
  :custom
  (vertico-scroll-margin 0)
  (vertico-count 20)
  (vertico-resize t)
  (vertico-cycle t)
  :bind (:map vertico-map
              ("C-j" . vertico-next)
              ("C-M-j" . vertico-next-group)
              ("C-k" . vertico-previous)
              ("C-M-k" . vertico-previous-group))
  :init
  (vertico-mode t))

(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles partial-completion))))
  (completion-category-defaults nil)
  (completion-pcm-leading-wildcard t))

(use-package marginalia
  :after compat
  :bind (:map minibuffer-local-map
              ("M-A" . marginalia-cycle))
  :hook (after-init . marginalia-mode))

(use-package embark
  :commands (embark-act
             embark-dwim
             embark-export
             embark-collect
             embark-bindings
             embark-prefix-help-command)
  :bind (("C-." . embark-act)
         ("C-;" . embark-dwim)
         ("C-h B" . embark-bindings))
  :init
  (setq prefix-help-command #'embark-prefix-help-command)
  :config
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))

(use-package embark-consult
  :hook (embark-collect-mode . consult-preview-at-point-mode))

(use-package consult
  :bind (("C-c M-x" . consult-mode-command)
         ("C-c h" . consult-history)
         ("C-c k" . consult-kmacro)
         ("C-c m" . consult-man)
         ("C-c i" . consult-info)
         ([remap Info-search] . consult-info)
         ("C-x M-:" . consult-complex-command)
         ("C-x b" . consult-buffer)
         ("C-x 4 b" . consult-buffer-other-window)
         ("C-x 5 b" . consult-buffer-other-frame)
         ("C-x t b" . consult-buffer-other-tab)
         ("C-x r b" . consult-bookmark)
         ("C-x p b" . consult-project-buffer)
         ("M-#" . consult-register-load)
         ("M-'" . consult-register-store)
         ("C-M-#" . consult-register)
         ("M-y" . consult-yank-pop)
         ("M-g e" . consult-compile-error)
         ("M-g r" . consult-grep-match)
         ("M-g f" . consult-flymake)
         ("M-g g" . consult-goto-line)
         ("M-g M-g" . consult-goto-line)
         ("M-g o" . consult-outline)
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ("M-s d" . consult-find)
         ("M-s c" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("C-s" . consult-line)
         ("M-s L" . consult-line-multi)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines)
         ("M-s e" . consult-isearch-history)
         :map isearch-mode-map
         ("M-e" . consult-isearch-history)
         ("M-s e" . consult-isearch-history)
         ("M-s l" . consult-line)
         ("M-s L" . consult-line-multi)
         :map minibuffer-local-map
         ("M-s" . consult-history)
         ("M-r" . consult-history))
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :init
  (advice-add #'register-preview :override #'consult-register-window)
  (setq register-preview-delay 0.5)
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
  :config
  (consult-customize
   consult-theme :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep consult-man
   consult-bookmark consult-recent-file consult-xref
   consult-source-bookmark consult-source-file-register
   consult-source-recent-file consult-source-project-recent-file
   :preview-key '(:debounce 0.4 any))
  (setq consult-narrow-key "<")
  (keymap-set consult-narrow-map (concat consult-narrow-key " ?") #'consult-narrow-help))

(defvar glz/git-map (make-sparse-keymap) "Leader sub-keymap for git commands.")
(define-key glz/git-map "g" #'magit-status)

(defvar glz/buffer-map (make-sparse-keymap) "Leader sub-keymap for buffer commands.")
(define-key glz/buffer-map "b" #'consult-buffer)
(define-key glz/buffer-map "p" #'previous-buffer)
(define-key glz/buffer-map "n" #'next-buffer)
(define-key glz/buffer-map "k" #'kill-current-buffer)

(defvar glz/toggle-map (make-sparse-keymap) "Leader sub-keymap for toggles.")
(define-key glz/toggle-map "l" #'display-line-numbers-mode)

(defvar glz/org-map (make-sparse-keymap) "Leader sub-keymap for org commands.")
(define-key glz/org-map "c" #'org-capture)

(when glz/enable-testfall
  (define-key glz/toggle-map "t" #'testfall-mode))

(when glz/enable-org-roam
  (defvar glz/org-roam-map (make-sparse-keymap) "Leader sub-keymap for org-roam.")
  (define-key glz/org-roam-map "c" #'org-roam-capture)
  (define-key glz/org-roam-map "f" #'org-roam-node-find)
  (define-key glz/org-roam-map "i" #'org-roam-node-insert)
  (define-key glz/org-roam-map "a" #'org-roam-node-insert-immediate)
  (define-key glz/org-roam-map "u" #'org-roam-ui-open)
  (define-key glz/org-roam-map "b" #'org-roam-buffer-toggle)
  (define-key glz/org-map "r" glz/org-roam-map))

(use-package meow
  :ensure t
  :demand t
  :config
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

  (meow-motion-overwrite-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))

  (meow-leader-define-key
   '("." . find-file)
   '("SPC" . project-find-file)
   (cons "g" glz/git-map)
   (cons "b" glz/buffer-map)
   (cons "t" glz/toggle-map)
   (cons "o" glz/org-map)
   '("h" . "C-h")
   '("p" . "C-x p")
   '("c" . (lambda () (interactive)
              (find-file (expand-file-name
                          (concat user-emacs-directory "Config.org")))))
   '("s" . eshell)
   '("?" . meow-cheatsheet))

  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore))

  (meow-setup-line-number)
  (meow-global-mode 1))

(defun glz/org-babel-tangle-config ()
  (when (and (buffer-file-name)
             (string-match-p "Config\\.org$" (buffer-file-name)))
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook
          (lambda ()
            (add-hook 'after-save-hook #'glz/org-babel-tangle-config nil t)))

(defun glz/org-mode-setup ()
  "Personal adjustments for org-mode."
  (org-indent-mode)
  (variable-pitch-mode 1)
  (auto-fill-mode 0)
  (visual-line-mode 1)
)

(use-package org
  :commands (org-mode org-version)
  :mode ("\\.org\\'" . org-mode)
  :hook (org-mode . glz/org-mode-setup)
  :config
  (setq org-ellipsis " ▾"
        org-hide-emphasis-markers t)

  ;; Fixed-pitch faces for code and special elements
  (require 'org-indent)
  (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
  (set-face-attribute 'org-code nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))
  (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)

  ;; Org Tempo snippets
  (require 'org-tempo)
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))

  ;; Replace list hyphen with bullet dot
  (font-lock-add-keywords 'org-mode
                          '(("^ *\\([-]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1)
                                                          (match-end 1) "•"))))))
  :custom
  (org-hide-leading-stars t)
  (org-startup-indented t)
  (org-adapt-indentation nil)
  (org-edit-src-content-indentation 0)
  (org-startup-truncated t))

(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

(defun glz/org-mode-visual-fill ()
  (setq visual-fill-column-width 150
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook (org-mode . glz/org-mode-visual-fill))

(setq org-directory glz/org-directory)
(setq org-agenda-files '("Tasks.org" "Birthdays.org" "Calendar.org"))

(setq org-agenda-start-with-log-mode t)
(setq org-log-done 'time)
(setq org-log-into-drawer t)

(setq org-todo-keywords
      '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
        (sequence "IDEA(i)" "DISCUSSION(d)" "ANALYSIS(a)" "IN WORK(w)" "|" "DONE(d!)" "CANCELLED(c!)")))

(setq org-agenda-custom-commands
      '(("d" "Dashboard"
         ((agenda "" ((org-deadline-warning-days 7)))
          (todo "NEXT"
                ((org-agenda-overriding-header "Next Tasks")))
          (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

        ("n" "Next Tasks"
         ((todo "NEXT"
                ((org-agenda-overriding-header "Next Tasks")))))

        ("W" "Work Tasks" tags-todo "+work")

        ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
         ((org-agenda-overriding-header "Low Effort Tasks")
          (org-agenda-max-todos 20)
          (org-agenda-files org-agenda-files)))

        ("w" "Workflow Status"
         ((todo "WAIT"
                ((org-agenda-overriding-header "Waiting on External")
                 (org-agenda-files org-agenda-files)))
          (todo "REVIEW"
                ((org-agenda-overriding-header "In Review")
                 (org-agenda-files org-agenda-files)))
          (todo "PLAN"
                ((org-agenda-overriding-header "In Planning")
                 (org-agenda-todo-list-sublevels nil)
                 (org-agenda-files org-agenda-files)))
          (todo "BACKLOG"
                ((org-agenda-overriding-header "Project Backlog")
                 (org-agenda-todo-list-sublevels nil)
                 (org-agenda-files org-agenda-files)))
          (todo "READY"
                ((org-agenda-overriding-header "Ready for Work")
                 (org-agenda-files org-agenda-files)))
          (todo "ACTIVE"
                ((org-agenda-overriding-header "Active Projects")
                 (org-agenda-files org-agenda-files)))
          (todo "COMPLETED"
                ((org-agenda-overriding-header "Completed Projects")
                 (org-agenda-files org-agenda-files)))
          (todo "CANC"
                ((org-agenda-overriding-header "Cancelled Projects")
                 (org-agenda-files org-agenda-files)))))))

(setq org-refile-targets '(("Archive.org" :maxlevel . 1)))
(advice-add 'org-refile :after 'org-save-all-org-buffers)

(setq org-capture-templates
      `(("t" "Task" entry (file+olp ,(concat glz/org-directory "Tasks.org") "Tasks")
         "* TODO %?\n  %U\n  %a\n  %i")
        ("b" "Birthday" entry (file ,(concat glz/org-directory "Birthdays.org"))
         "* %?\n  %^t\n %i")))

(when glz/enable-org-roam
  (use-package org-roam
    :after org
    :commands (org-roam-buffer-toggle
               org-roam-node-find
               org-roam-graph
               org-roam-node-insert
               org-roam-capture)
    :custom
    (org-roam-directory (file-truename (concat org-directory "roam/")))
    :bind (("C-c n l" . org-roam-buffer-toggle)
           ("C-c n f" . org-roam-node-find)
           ("C-c n g" . org-roam-graph)
           ("C-c n i" . org-roam-node-insert)
           ("C-c n c" . org-roam-capture)
           ("C-c n j" . org-roam-dailies-capture-today))
    :config
    (setq org-roam-node-display-template
          (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
    (when (file-directory-p org-roam-directory)
      (org-roam-db-autosync-mode))
    (require 'org-roam-protocol))

  (defun org-roam-node-insert-immediate (arg &rest args)
    "Insert an org-roam node without opening a capture buffer."
    (interactive "P")
    (let ((args (cons arg args))
          (org-roam-capture-templates
           (list (append (car org-roam-capture-templates)
                         '(:immediate-finish t)))))
      (apply #'org-roam-node-insert args))))

(when glz/enable-org-roam
  (use-package org-roam-ui
    :after org-roam
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t)))

(use-package org-download
  :commands (org-download-clipboard org-download-yank org-download-enable)
  :hook (dired-mode . org-download-enable))

(use-package dired
  :ensure nil
  :defer t
  :hook (dired-mode . dired-hide-details-mode)
  :config
  (setq dired-dwim-target t)
  (setq dired-recursive-copies 'always)
  (setq dired-create-destination-dirs 'ask)
  (setq dired-clean-confirm-killing-deleted-buffers nil)
  (setq dired-make-directory-clickable t)
  (setq dired-mouse-drag-files t))

(use-package all-the-icons-dired
  :hook (dired-mode . all-the-icons-dired-mode))

(setq ediff-keep-variants nil)
(setq ediff-make-buffers-readonly-at-startup nil)
(setq ediff-merge-revisions-with-ancestor t)
(setq ediff-show-clashes-only t)
(setq ediff-split-window-function 'split-window-horizontally)
(setq ediff-window-setup-function 'ediff-setup-windows-plain)

;; On Windows, prefer the Git-bundled diff/diff3 as an explicit fallback
;; in case exec-path doesn't resolve them yet when ediff loads.
(when (eq glz/platform 'windows)
  (let ((diff  (or (executable-find "diff")
                   "C:/Program Files/Git/usr/bin/diff.exe"))
        (diff3 (or (executable-find "diff3")
                   "C:/Program Files/Git/usr/bin/diff3.exe")))
    (setq ediff-diff-program  diff
          ediff-diff3-program diff3)))

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

(use-package which-key
  :ensure nil
  :hook (after-init . which-key-mode)
  :config
  (setq which-key-idle-delay 0.3)
  (which-key-add-keymap-based-replacements mode-specific-map
    "g" "git"
    "b" "buffers"
    "t" "toggles"
    "o" "org"
    "o r" "org-roam"))

(use-package helpful
  :commands (helpful-callable
             helpful-variable
             helpful-key
             helpful-command
             helpful-at-point
             helpful-function)
  :bind ([remap describe-command] . helpful-command)
  :bind ([remap describe-function] . helpful-callable)
  :bind ([remap describe-key] . helpful-key)
  :bind ([remap describe-symbol] . helpful-symbol)
  :bind ([remap describe-variable] . helpful-variable)
  :custom (helpful-max-buffers 7))

(use-package no-littering
  :demand t)

(use-package magit
  :commands (magit-status magit-get-current-branch)
  :custom
  (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

(when glz/enable-forge
  (use-package forge
    :after magit))

(when glz/enable-nix
  (use-package nix-mode
    :mode "\\.nix\\'"))

(when glz/enable-testfall
  (let ((f (expand-file-name "testfall-mode.el" user-emacs-directory)))
    (if (file-exists-p f) (load-file f)
      (message "Warning: %s not found, skipping testfall-mode" f)))

  (defun glz/testfall-buffer-p ()
    "Return non-nil if the buffer content matches testfall grammar patterns."
    (save-excursion
      (save-restriction
        (widen)
        (goto-char (point-min))
        ;; Match patterns that are highly distinctive to testfall files
        (re-search-forward
         (rx (or "<Konzern-Varianten>"
                 (seq "DUT::" (+ (any alpha "_")))
                 (seq "VAR::" (+ (any alpha "_")))
                 (seq "CAL::" (+ (any alpha "_")))
                 (seq bol "Variation:")
                 (seq bol "VarEnd")))
         (min (point-max) 100000)
         t))))

  (defun glz/maybe-enable-testfall-mode ()
    "Enable testfall-base-mode when the buffer contains testfall grammar."
    (when (and buffer-file-name
               (not (string-match-p "\\.org\\'" buffer-file-name))
               (not (derived-mode-p 'testfall-base-mode))
               (glz/testfall-buffer-p))
      (testfall-base-mode)))

  (add-hook 'find-file-hook #'glz/maybe-enable-testfall-mode))

(when glz/enable-anforderungen
  (let ((f (expand-file-name "anforderungen-mode.el" user-emacs-directory)))
    (if (file-exists-p f) (load-file f)
      (message "Warning: %s not found, skipping anforderungen-mode" f))))

(when glz/enable-canape-par
  (let ((f (expand-file-name "canape-par-mode.el" user-emacs-directory)))
    (if (file-exists-p f) (load-file f)
      (message "Warning: %s not found, skipping canape-par-mode" f))))

(load custom-file 'noerror 'no-message)
